// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// build_Ainv_sparse_RA
Rcpp::List build_Ainv_sparse_RA(const Rcpp::IntegerVector& sire, const Rcpp::IntegerVector& dam);
RcppExport SEXP _connectedness_build_Ainv_sparse_RA(SEXP sireSEXP, SEXP damSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type sire(sireSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dam(damSEXP);
    rcpp_result_gen = Rcpp::wrap(build_Ainv_sparse_RA(sire, dam));
    return rcpp_result_gen;
END_RCPP
}
// cd_contrast_mu_mme_sparse
Rcpp::List cd_contrast_mu_mme_sparse(const Eigen::SparseMatrix<double>& Ainv, const Rcpp::IntegerVector& id_rec, const Eigen::SparseMatrix<double>& X, const Rcpp::IntegerVector& mu_animal, Rcpp::Nullable<Rcpp::LogicalVector> target_nullable, double sigma2a, double sigma2e, Rcpp::Nullable<Rcpp::CharacterVector> mu_names_nullable);
RcppExport SEXP _connectedness_cd_contrast_mu_mme_sparse(SEXP AinvSEXP, SEXP id_recSEXP, SEXP XSEXP, SEXP mu_animalSEXP, SEXP target_nullableSEXP, SEXP sigma2aSEXP, SEXP sigma2eSEXP, SEXP mu_names_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type Ainv(AinvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type id_rec(id_recSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mu_animal(mu_animalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::LogicalVector> >::type target_nullable(target_nullableSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2a(sigma2aSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2e(sigma2eSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type mu_names_nullable(mu_names_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(cd_contrast_mu_mme_sparse(Ainv, id_rec, X, mu_animal, target_nullable, sigma2a, sigma2e, mu_names_nullable));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_connectedness_build_Ainv_sparse_RA", (DL_FUNC) &_connectedness_build_Ainv_sparse_RA, 2},
    {"_connectedness_cd_contrast_mu_mme_sparse", (DL_FUNC) &_connectedness_cd_contrast_mu_mme_sparse, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_connectedness(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
