// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// build_Ainv_sparse_RA
Rcpp::List build_Ainv_sparse_RA(const Rcpp::IntegerVector& sire, const Rcpp::IntegerVector& dam);
RcppExport SEXP _connectedness_build_Ainv_sparse_RA(SEXP sireSEXP, SEXP damSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type sire(sireSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dam(damSEXP);
    rcpp_result_gen = Rcpp::wrap(build_Ainv_sparse_RA(sire, dam));
    return rcpp_result_gen;
END_RCPP
}

// compute_Ginv
Rcpp::List compute_Ginv(const Eigen::MatrixXi& X, double maf_threshold, int missing_code, double blend, int chunk_size, int n_threads, int tunedG, Rcpp::Nullable<Rcpp::NumericMatrix> A22);
RcppExport SEXP _connectedness_compute_Ginv(SEXP XSEXP, SEXP maf_thresholdSEXP, SEXP missing_codeSEXP, SEXP blendSEXP, SEXP chunk_sizeSEXP, SEXP n_threadsSEXP, SEXP tunedGSEXP, SEXP A22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type maf_threshold(maf_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< double >::type blend(blendSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type tunedG(tunedGSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type A22(A22SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Ginv(X, maf_threshold, missing_code, blend, chunk_size, n_threads, tunedG, A22));
    return rcpp_result_gen;
END_RCPP
}

// compute_Hinv_from_X
Rcpp::List compute_Hinv_from_X(const Rcpp::IntegerVector& sire, const Rcpp::IntegerVector& dam, const Rcpp::IntegerVector& genotyped_idx, const Eigen::MatrixXi& X, double maf_threshold, int missing_code, double blend, int chunk_size, int n_threads, int tunedG, double tau, double omega, bool return_Ainv, bool return_F, bool return_A22, bool return_Ginv, bool return_allele_freqs, bool verbose);
RcppExport SEXP _connectedness_compute_Hinv_from_X(SEXP sireSEXP, SEXP damSEXP, SEXP genotyped_idxSEXP, SEXP XSEXP, SEXP maf_thresholdSEXP, SEXP missing_codeSEXP, SEXP blendSEXP, SEXP chunk_sizeSEXP, SEXP n_threadsSEXP, SEXP tunedGSEXP, SEXP tauSEXP, SEXP omegaSEXP, SEXP return_AinvSEXP, SEXP return_FSEXP, SEXP return_A22SEXP, SEXP return_GinvSEXP, SEXP return_allele_freqsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type sire(sireSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dam(damSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type genotyped_idx(genotyped_idxSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type maf_threshold(maf_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< double >::type blend(blendSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type tunedG(tunedGSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< bool >::type return_Ainv(return_AinvSEXP);
    Rcpp::traits::input_parameter< bool >::type return_F(return_FSEXP);
    Rcpp::traits::input_parameter< bool >::type return_A22(return_A22SEXP);
    Rcpp::traits::input_parameter< bool >::type return_Ginv(return_GinvSEXP);
    Rcpp::traits::input_parameter< bool >::type return_allele_freqs(return_allele_freqsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Hinv_from_X(sire, dam, genotyped_idx, X, maf_threshold, missing_code, blend, chunk_size, n_threads, tunedG, tau, omega, return_Ainv, return_F, return_A22, return_Ginv, return_allele_freqs, verbose));
    return rcpp_result_gen;
END_RCPP
}

// cd_contrast_mu_mme_sparse
Rcpp::List cd_contrast_mu_mme_sparse(const Eigen::SparseMatrix<double>& Ainv, const Rcpp::IntegerVector& id_rec, const Eigen::SparseMatrix<double>& X, const Rcpp::IntegerVector& mu_animal, Rcpp::Nullable<Rcpp::LogicalVector> target_nullable, double sigma2a, double sigma2e, Rcpp::Nullable<Rcpp::CharacterVector> mu_names_nullable);
RcppExport SEXP _connectedness_cd_contrast_mu_mme_sparse(SEXP AinvSEXP, SEXP id_recSEXP, SEXP XSEXP, SEXP mu_animalSEXP, SEXP target_nullableSEXP, SEXP sigma2aSEXP, SEXP sigma2eSEXP, SEXP mu_names_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type Ainv(AinvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type id_rec(id_recSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mu_animal(mu_animalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::LogicalVector> >::type target_nullable(target_nullableSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2a(sigma2aSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2e(sigma2eSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type mu_names_nullable(mu_names_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(cd_contrast_mu_mme_sparse(Ainv, id_rec, X, mu_animal, target_nullable, sigma2a, sigma2e, mu_names_nullable));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_connectedness_build_Ainv_sparse_RA", (DL_FUNC) &_connectedness_build_Ainv_sparse_RA, 2},
    {"_connectedness_compute_Ginv", (DL_FUNC) &_connectedness_compute_Ginv, 8},
    {"_connectedness_compute_Hinv_from_X", (DL_FUNC) &_connectedness_compute_Hinv_from_X, 18},
    {"_connectedness_cd_contrast_mu_mme_sparse", (DL_FUNC) &_connectedness_cd_contrast_mu_mme_sparse, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_connectedness(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
