# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute inbreeding coefficients via an ML92-style traversal
NULL

#' Build sparse A-inverse from a renumbered pedigree
NULL

#' Build the dense A22 submatrix for genotyped animals
NULL

#' Compute dense G-inverse for genotyped animals (VanRaden method 1)
NULL

#' Compute sparse H-inverse for a combined pedigree-genomic relationship model
NULL

#' Compute full H-inverse pipeline from pedigree and genotypes
NULL

compute_F_ML92 <- function(sire, dam) {
    .Call(`_connectedness_compute_F_ML92`, sire, dam)
}

build_Ainv_sparse_RA <- function(sire, dam) {
    .Call(`_connectedness_build_Ainv_sparse_RA`, sire, dam)
}

build_A22 <- function(sire, dam, genotyped_idx, F, verbose = TRUE) {
    .Call(`_connectedness_build_A22`, sire, dam, genotyped_idx, F, verbose)
}

compute_Ginv <- function(X, maf_threshold = 0.05, missing_code = 5L, blend = 0.05, chunk_size = 2000L, n_threads = 1L, tunedG = 0L, A22 = NULL) {
    .Call(`_connectedness_compute_Ginv`, X, maf_threshold, missing_code, blend, chunk_size, n_threads, tunedG, A22)
}

compute_Hinv <- function(Ainv, Ginv, A22, genotyped_idx, tau = 1.0, omega = 1.0) {
    .Call(`_connectedness_compute_Hinv`, Ainv, Ginv, A22, genotyped_idx, tau, omega)
}

compute_Hinv_from_X <- function(sire, dam, genotyped_idx, X, maf_threshold = 0.05, missing_code = 5L, blend = 0.05, chunk_size = 2000L, n_threads = 1L, tunedG = 0L, tau = 1.0, omega = 1.0, return_Ainv = FALSE, return_F = FALSE, return_A22 = FALSE, return_Ginv = FALSE, return_allele_freqs = FALSE) {
    .Call(`_connectedness_compute_Hinv_from_X`, sire, dam, genotyped_idx, X, maf_threshold, missing_code, blend, chunk_size, n_threads, tunedG, tau, omega, return_Ainv, return_F, return_A22, return_Ginv, return_allele_freqs)
}

#' Compute CD and PEVD via MME contrast using a generic inverse relationship matrix
#'
#' This function computes connectedness statistics using a generic inverse
#' relationship/covariance matrix for the animal effect, denoted here as
#' \eqn{K^{-1}}. Therefore, it can be used with:
#' \itemize{
#'   \item \code{Ainv} for pedigree-based connectedness,
#'   \item \code{Hinv} for connectedness under a combined pedigree-genomic kernel,
#'   \item or any other compatible inverse kernel matrix.
#' }
#'
#' The model is:
#' \deqn{y = Xb + Zu + e}
#' with
#' \deqn{u \sim N(0, K \sigma_a^2), \quad e \sim N(0, I \sigma_e^2)}
#'
#' so the MME animal block is built as:
#' \deqn{Z'Z + \lambda K^{-1}}, \quad \lambda = \sigma_e^2 / \sigma_a^2
#'
#' @param Kinv Sparse N x N inverse relationship/covariance matrix
#'   (e.g. Ainv or Hinv; dgCMatrix).
#' @param id_rec Integer vector (length nrec) with animal index (1..N) for
#'   each phenotypic record.
#' @param X Sparse model matrix for fixed effects (nrec x p, dgCMatrix).
#' @param mu_animal Integer vector (length N): MU index (1..U) per animal;
#'   0 = not a target animal.
#' @param target_nullable Logical vector (length N) indicating target animals,
#'   or NULL to include all animals with mu_animal > 0.
#' @param sigma2a Additive genetic variance (or more generally, variance of u).
#' @param sigma2e Residual variance.
#' @param mu_names_nullable Optional character vector of MU names (length U).
#' @return List with CD, PEVD, qK, qC matrices (U x U) and n_target_by_MU.
#' @keywords internal
#' @noRd
cd_contrast_mu_mme_sparse <- function(Kinv, id_rec, X, mu_animal, target_nullable, sigma2a, sigma2e, mu_names_nullable = NULL) {
    .Call(`_connectedness_cd_contrast_mu_mme_sparse`, Kinv, id_rec, X, mu_animal, target_nullable, sigma2a, sigma2e, mu_names_nullable)
}
